### ISSUE TITLE
Queso + autotools doesn't work as expected

### ISSUE THREAD

**Issue by moprak** [libqueso/queso#415] opened 2016-01-13 23:29 UTC
queso_new.m4 does not supply CFLAGS/LIBS from it's dependencies. This doesn't work with autotools since queso references headers/libs from it's dependencies and requires the user to figure out what queso was complied with and add those.

**Comment by pbauman** [comment] 2016-01-13 23:40
This is typically taken care of libtool (libqueso.la file). What's the use case your hitting here?

**Comment by moprak** [comment] 2016-01-14 03:34
Ah, I guess it's just the headers then - queso includes headers from gsl, boost etc. But the compiler won't get a -I GSL_INC -I BOOST_INC and will hence not compile.

**Comment by pbauman** [comment] 2016-01-14 13:41
I presume you're talking about building a standalone application that links with QUESO? In this case, that's correct. This is because QUESO hasn't implemented a proper PIMPL idiom for the GSL wrappers. This is something I've talked about with @dmcdougall, just haven't found developer time for it. It'd be easy to do if you want to take a stab at it. ;-)

**Comment by moprak** [comment] 2016-01-14 14:42
Yeah, it's a standalone application that links to QUESO (and in my case GSL too). But, I dont think just having GSL wrappers is sufficient, I had to add Boost and GLPK header paths too. I'd imagine the headers that need to be added will depend on what QUESO was complied with (Trilinos for instance).  I'd take a stab at fixing it, but considering I know nada about most of the machinery, I'll have to pass :-)

**Comment by dmcdougall** [comment] 2016-07-23 01:08
I'm closing this as a duplicate of #240 and #256.

**Closed by dmcdougall** 2016-07-23 01:08 UTC
